version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    entrypoint: ["/bin/sh", "-c", "rm -rf /usr/share/elasticsearch/data/* && /usr/local/bin/docker-entrypoint.sh"]

volumes:
  elasticsearch-data:
    driver: local
